export const wishlistInfo = [
    {   id:1,
        name:"Sedon Series",
        rating:4.9,
        status:"New",
        price:"190,000",
        liked:true,
        imageUrl:require("../../assets/images/car-1.png"),
    },
    {
        id:2,
        name:"McLaren Supercar",
        rating:4.6,
        status:"Used",
        price:"133,000",
        liked:true,
        imageUrl:require("../../assets/images/car-2.png"),
    },
    {
        id:3,
        name:"BMW Series",
        rating:4.7,
        status:"Used",
        price:"170,000",
        liked:true,
        imageUrl:require("../../assets/images/car-3.png"),
    },
    {
        id:4,
        name:"F-type Jaguar",
        rating:4.9,
        status:"New",
        price:"167,000",
        liked:true,
        imageUrl:require("../../assets/images/car-4.png"),
    },
    {
        id:5,
        name:"Ford",
        rating:4.3,
        status:"New",
        price:"25,000",
        liked:true,
        imageUrl:require("../../assets/images/car-5.png"),
    },
    {
        id:6,
        name:"Classic Frog",
        rating:4.5,
        status:"Used",
        price:"155,000",
        liked:true,
        imageUrl:require("../../assets/images/car-6.png"),
    },
    {   id:7,
        name:"BMW M5 Series",
        rating:4.9,
        status:"New",
        price:"190,000",
        liked:false,
        imageUrl:require("../../assets/images/car-01.png"),
    },
    {
        id:8,
        name:"McLaren Supercar",
        rating:4.6,
        status:"Used",
        price:"133,000",
        liked:false,
        imageUrl:require("../../assets/images/car-02.png"),
    },
    {
        id:9,
        name:"BMW Series Sports",
        rating:4.7,
        status:"Used",
        price:"170,000",
        liked:false,
        imageUrl:require("../../assets/images/car-03.png"),
    },
    {
        id:10,
        name:"F-type Jaguar Sports",
        rating:4.9,
        status:"New",
        price:"167,000",
        liked:false,
        imageUrl:require("../../assets/images/car-04.png"),
    },
    {
        id:11,
        name:"Ford",
        rating:4.3,
        status:"New",
        price:"25,000",
        liked:false,
        imageUrl:require("../../assets/images/car-05.png"),
    },
    {
        id:12,
        name:"Classic Frog Sports",
        rating:4.5,
        status:"Used",
        price:"155,000",
        liked:false,
        imageUrl:require("../../assets/images/car-06.png"),
    },
]

